/* -------- countries + top cities -------- */
type Country = {
  code: string;
  flag: string;
  name: string;
  cities: string[];
};

export const COUNTRIES: Country[] = [
  {
    code: "US",
    flag: "🇺🇸",
    name: "United States",
    cities: [
      "san francisco",
      "new york",
      "seattle",
      "austin",
      "boston",
      "los angeles",
      "chicago",
      "denver",
      "atlanta",
      "san diego",
    ],
  },
  {
    code: "UK",
    flag: "🇬🇧",
    name: "United Kingdom",
    cities: [
      "london",
      "manchester",
      "cambridge",
      "oxford",
      "edinburgh",
      "bristol",
      "birmingham",
      "leeds",
      "glasgow",
      "brighton",
    ],
  },
  {
    code: "DE",
    flag: "🇩🇪",
    name: "Germany",
    cities: [
      "berlin",
      "munich",
      "hamburg",
      "frankfurt",
      "stuttgart",
      "cologne",
      "düsseldorf",
      "leipzig",
      "dresden",
      "nuremberg",
    ],
  },
  {
    code: "CH",
    flag: "🇨🇭",
    name: "Switzerland",
    cities: [
      "zurich",
      "geneva",
      "lausanne",
      "basel",
      "bern",
      "zug",
      "winterthur",
      "lucerne",
      "st. gallen",
      "lugano",
    ],
  },
  {
    code: "IE",
    flag: "🇮🇪",
    name: "Ireland",
    cities: [
      "dublin",
      "cork",
      "galway",
      "limerick",
      "waterford",
      "kilkenny",
      "swords",
      "kildare",
      "louth",
      "wicklow",
    ],
  },
  {
    code: "NL",
    flag: "🇳🇱",
    name: "Netherlands",
    cities: [
      "amsterdam",
      "rotterdam",
      "the hague",
      "eindhoven",
      "utrecht",
      "tilburg",
      "groningen",
      "almere",
      "breda",
      "nijmegen",
    ],
  },
  {
    code: "FR",
    flag: "🇫🇷",
    name: "France",
    cities: [
      "paris",
      "lyon",
      "marseille",
      "toulouse",
      "lille",
      "bordeaux",
      "nantes",
      "strasbourg",
      "nice",
      "rennes",
    ],
  },
  {
    code: "CA",
    flag: "🇨🇦",
    name: "Canada",
    cities: [
      "toronto",
      "vancouver",
      "montreal",
      "ottawa",
      "calgary",
      "edmonton",
      "waterloo",
      "victoria",
      "mississauga",
      "quebec city",
    ],
  },
  {
    code: "SE",
    flag: "🇸🇪",
    name: "Sweden",
    cities: [
      "stockholm",
      "gothenburg",
      "malmö",
      "uppsala",
      "västerås",
      "örebro",
      "linköping",
      "helsingborg",
      "umeå",
      "lund",
    ],
  },
  {
    code: "ES",
    flag: "🇪🇸",
    name: "Spain",
    cities: [
      "barcelona",
      "madrid",
      "valencia",
      "seville",
      "bilbao",
      "malaga",
      "alicante",
      "zaragoza",
      "granada",
      "palma",
    ],
  },
];
